# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0002_auto_20170426_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_destination', models.CharField(max_length=255)),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField()),
                ('travel_plan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
