# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0003_auto_20170426_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='travel_plan',
            new_name='travel_description',
        ),
    ]
