# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0004_auto_20170426_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_end_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_start_date',
            field=models.CharField(max_length=255),
        ),
    ]
