# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0005_auto_20170426_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='joined_users',
            field=models.ManyToManyField(related_name='joined_users', to='APPNAME.User'),
        ),
    ]
